FROM node:22-alpine

WORKDIR /app

# Install dependencies first for better caching
COPY package*.json ./
RUN npm install --production

# Copy environment file if present and then the rest of the backend source code
COPY .env ./.env
COPY . .

# Expose the port your Express server uses
EXPOSE 5000

# Start the server
CMD ["node", "server.js"]
